language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - test/build.sh
