language: php

cache:
  directories:
  - $HOME/.composer/cache/

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - 7.1
  - nightly

before_install:
  - if [ ${TRAVIS_PHP_VERSION:0:4} != "hhvm" ] && [ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]; then phpenv config-rm xdebug.ini; fi

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - composer validate
  - test/build.sh
